/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'
import { Route as ApiPublicHooksTradeTickRouteImport } from './routes/api/public/hooks/trade-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTradeTickRoute = ApiPublicHooksTradeTickRouteImport.update({
  id: '/api/public/hooks/trade-tick',
  path: '/api/public/hooks/trade-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/hooks/scan' | '/api/public/hooks/trade-tick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/scan' | '/api/public/hooks/trade-tick'
  id:
    '__root__' | '/' | '/api/public/hooks/scan' | '/api/public/hooks/trade-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
  ApiPublicHooksTradeTickRoute: typeof ApiPublicHooksTradeTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trade-tick': {
      id: '/api/public/hooks/trade-tick'
      path: '/api/public/hooks/trade-tick'
      fullPath: '/api/public/hooks/trade-tick'
      preLoaderRoute: typeof ApiPublicHooksTradeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
  ApiPublicHooksTradeTickRoute: ApiPublicHooksTradeTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
