/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as ApiPublicHooksScanRouteImport } from './routes/api/public/hooks/scan'
import { Route as ApiPublicHooksSyncTradesRouteImport } from './routes/api/public/hooks/sync-trades'
import { Route as ApiPublicHooksTradeTickRouteImport } from './routes/api/public/hooks/trade-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScanRoute = ApiPublicHooksScanRouteImport.update({
  id: '/api/public/hooks/scan',
  path: '/api/public/hooks/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncTradesRoute =
  ApiPublicHooksSyncTradesRouteImport.update({
    id: '/api/public/hooks/sync-trades',
    path: '/api/public/hooks/sync-trades',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTradeTickRoute = ApiPublicHooksTradeTickRouteImport.update({
  id: '/api/public/hooks/trade-tick',
  path: '/api/public/hooks/trade-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/sync-trades': typeof ApiPublicHooksSyncTradesRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/sync-trades': typeof ApiPublicHooksSyncTradesRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/trades': typeof TradesRoute
  '/api/public/hooks/scan': typeof ApiPublicHooksScanRoute
  '/api/public/hooks/sync-trades': typeof ApiPublicHooksSyncTradesRoute
  '/api/public/hooks/trade-tick': typeof ApiPublicHooksTradeTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/trades'
    | '/api/public/hooks/scan'
    | '/api/public/hooks/sync-trades'
    | '/api/public/hooks/trade-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/trades'
    | '/api/public/hooks/scan'
    | '/api/public/hooks/sync-trades'
    | '/api/public/hooks/trade-tick'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/trades'
    | '/api/public/hooks/scan'
    | '/api/public/hooks/sync-trades'
    | '/api/public/hooks/trade-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TradesRoute: typeof TradesRoute
  ApiPublicHooksScanRoute: typeof ApiPublicHooksScanRoute
  ApiPublicHooksSyncTradesRoute: typeof ApiPublicHooksSyncTradesRoute
  ApiPublicHooksTradeTickRoute: typeof ApiPublicHooksTradeTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan': {
      id: '/api/public/hooks/scan'
      path: '/api/public/hooks/scan'
      fullPath: '/api/public/hooks/scan'
      preLoaderRoute: typeof ApiPublicHooksScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-trades': {
      id: '/api/public/hooks/sync-trades'
      path: '/api/public/hooks/sync-trades'
      fullPath: '/api/public/hooks/sync-trades'
      preLoaderRoute: typeof ApiPublicHooksSyncTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trade-tick': {
      id: '/api/public/hooks/trade-tick'
      path: '/api/public/hooks/trade-tick'
      fullPath: '/api/public/hooks/trade-tick'
      preLoaderRoute: typeof ApiPublicHooksTradeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TradesRoute: TradesRoute,
  ApiPublicHooksScanRoute: ApiPublicHooksScanRoute,
  ApiPublicHooksSyncTradesRoute: ApiPublicHooksSyncTradesRoute,
  ApiPublicHooksTradeTickRoute: ApiPublicHooksTradeTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
